title: YJPARK's R&D Basecamp
author: Yunjeong Park
email: yjpark200421@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta
  (for Google search results) and in your feed.xml site description.
show_excerpts: true # true = 홈페이지 초기버전 보여줌
url: https://yjpark0421.github.io

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: YJPARK's R&D Basecamp
  tagline: Data Scientist. Data Analyst
  date_format: "%Y-%m-%d"
  style: black
  showNav: false
  showPicker: false
  useMathJax: true
  enable_mathjax: true
#   analytics_id: 'UA-159828029-1'

  # generate social links in footer
  social_links:
#     twitter: 
    github:  YJPark0421
#     linkedIn: in/
#     rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
remote_theme: thelehhman/texture
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
